[2023-02-18T07:48:31.505+0000] {processor.py:153} INFO - Started process (PID=98) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:48:31.509+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T07:48:31.585+0000] {logging_mixin.py:137} INFO - [2023-02-18T07:48:31.584+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:48:32.206+0000] {logging_mixin.py:137} INFO - [2023-02-18T07:48:32.171+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 10, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T07:48:32.207+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:48:33.434+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 2.055 seconds
[2023-02-18T07:49:57.667+0000] {processor.py:153} INFO - Started process (PID=175) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:49:57.699+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T07:49:57.701+0000] {logging_mixin.py:137} INFO - [2023-02-18T07:49:57.701+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:49:57.958+0000] {logging_mixin.py:137} INFO - [2023-02-18T07:49:57.928+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T07:49:57.959+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:49:58.980+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 1.376 seconds
[2023-02-18T07:50:50.579+0000] {processor.py:153} INFO - Started process (PID=225) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:50:50.664+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T07:50:50.666+0000] {logging_mixin.py:137} INFO - [2023-02-18T07:50:50.666+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:50:51.105+0000] {logging_mixin.py:137} INFO - [2023-02-18T07:50:51.033+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T07:50:51.107+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:50:52.070+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 1.718 seconds
[2023-02-18T07:51:46.908+0000] {processor.py:153} INFO - Started process (PID=270) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:51:46.941+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T07:51:46.956+0000] {logging_mixin.py:137} INFO - [2023-02-18T07:51:46.955+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:51:47.251+0000] {logging_mixin.py:137} INFO - [2023-02-18T07:51:47.248+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T07:51:47.266+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:51:48.337+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 1.634 seconds
[2023-02-18T07:52:39.031+0000] {processor.py:153} INFO - Started process (PID=319) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:52:39.093+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T07:52:39.096+0000] {logging_mixin.py:137} INFO - [2023-02-18T07:52:39.095+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:52:39.574+0000] {logging_mixin.py:137} INFO - [2023-02-18T07:52:39.570+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T07:52:39.654+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:52:40.394+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 1.396 seconds
[2023-02-18T07:53:23.416+0000] {processor.py:153} INFO - Started process (PID=362) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:53:23.449+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T07:53:23.453+0000] {logging_mixin.py:137} INFO - [2023-02-18T07:53:23.451+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:53:23.654+0000] {logging_mixin.py:137} INFO - [2023-02-18T07:53:23.640+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T07:53:23.655+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:53:23.990+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 0.638 seconds
[2023-02-18T07:54:06.581+0000] {processor.py:153} INFO - Started process (PID=402) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:54:06.832+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T07:54:06.834+0000] {logging_mixin.py:137} INFO - [2023-02-18T07:54:06.833+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:54:06.930+0000] {logging_mixin.py:137} INFO - [2023-02-18T07:54:06.916+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T07:54:06.931+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:54:07.380+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 0.961 seconds
[2023-02-18T07:54:53.211+0000] {processor.py:153} INFO - Started process (PID=450) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:54:53.227+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T07:54:53.229+0000] {logging_mixin.py:137} INFO - [2023-02-18T07:54:53.228+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:54:53.645+0000] {logging_mixin.py:137} INFO - [2023-02-18T07:54:53.642+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T07:54:53.646+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:54:55.004+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 1.874 seconds
[2023-02-18T07:55:57.933+0000] {processor.py:153} INFO - Started process (PID=500) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:55:57.983+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T07:55:58.187+0000] {logging_mixin.py:137} INFO - [2023-02-18T07:55:58.186+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:55:58.380+0000] {logging_mixin.py:137} INFO - [2023-02-18T07:55:58.372+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T07:55:58.381+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:55:59.248+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 1.692 seconds
[2023-02-18T07:57:56.319+0000] {processor.py:153} INFO - Started process (PID=572) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:57:56.366+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T07:57:56.369+0000] {logging_mixin.py:137} INFO - [2023-02-18T07:57:56.368+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:57:57.460+0000] {logging_mixin.py:137} INFO - [2023-02-18T07:57:57.413+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T07:57:57.494+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T07:57:59.052+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 3.145 seconds
[2023-02-18T08:00:52.921+0000] {processor.py:153} INFO - Started process (PID=685) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:00:52.975+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T08:00:52.977+0000] {logging_mixin.py:137} INFO - [2023-02-18T08:00:52.977+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:00:54.321+0000] {logging_mixin.py:137} INFO - [2023-02-18T08:00:54.178+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T08:00:54.368+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:00:55.564+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 2.979 seconds
[2023-02-18T08:04:10.272+0000] {processor.py:153} INFO - Started process (PID=805) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:04:10.415+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T08:04:10.418+0000] {logging_mixin.py:137} INFO - [2023-02-18T08:04:10.417+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:04:11.829+0000] {logging_mixin.py:137} INFO - [2023-02-18T08:04:11.826+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T08:04:11.831+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:04:13.944+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 3.767 seconds
[2023-02-18T08:08:56.635+0000] {processor.py:153} INFO - Started process (PID=966) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:08:56.683+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T08:08:56.777+0000] {logging_mixin.py:137} INFO - [2023-02-18T08:08:56.685+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:08:57.297+0000] {logging_mixin.py:137} INFO - [2023-02-18T08:08:57.266+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T08:08:57.300+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:08:57.985+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 1.773 seconds
[2023-02-18T08:12:20.991+0000] {processor.py:153} INFO - Started process (PID=1089) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:12:21.031+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T08:12:21.102+0000] {logging_mixin.py:137} INFO - [2023-02-18T08:12:21.091+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:12:21.781+0000] {logging_mixin.py:137} INFO - [2023-02-18T08:12:21.747+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T08:12:21.782+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:12:23.728+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 3.335 seconds
[2023-02-18T08:15:52.583+0000] {processor.py:153} INFO - Started process (PID=1214) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:15:52.624+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T08:15:52.724+0000] {logging_mixin.py:137} INFO - [2023-02-18T08:15:52.722+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:15:53.459+0000] {logging_mixin.py:137} INFO - [2023-02-18T08:15:53.363+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T08:15:53.461+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:15:54.602+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 2.755 seconds
[2023-02-18T08:18:57.999+0000] {processor.py:153} INFO - Started process (PID=1331) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:18:58.052+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T08:18:58.055+0000] {logging_mixin.py:137} INFO - [2023-02-18T08:18:58.054+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:18:59.090+0000] {logging_mixin.py:137} INFO - [2023-02-18T08:18:58.791+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T08:18:59.091+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:19:02.115+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 4.470 seconds
[2023-02-18T08:21:58.760+0000] {processor.py:153} INFO - Started process (PID=1444) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:21:58.941+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T08:21:58.944+0000] {logging_mixin.py:137} INFO - [2023-02-18T08:21:58.943+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:21:59.598+0000] {logging_mixin.py:137} INFO - [2023-02-18T08:21:59.495+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T08:21:59.600+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:22:00.904+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 2.310 seconds
[2023-02-18T08:24:58.435+0000] {processor.py:153} INFO - Started process (PID=1559) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:24:58.625+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T08:24:58.658+0000] {logging_mixin.py:137} INFO - [2023-02-18T08:24:58.657+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:25:02.018+0000] {logging_mixin.py:137} INFO - [2023-02-18T08:25:01.771+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T08:25:02.020+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:25:04.188+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 6.840 seconds
[2023-02-18T08:30:26.432+0000] {processor.py:153} INFO - Started process (PID=1730) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:30:26.529+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T08:30:26.532+0000] {logging_mixin.py:137} INFO - [2023-02-18T08:30:26.531+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:30:28.692+0000] {logging_mixin.py:137} INFO - [2023-02-18T08:30:28.690+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T08:30:28.694+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:30:34.675+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 9.059 seconds
[2023-02-18T08:39:08.248+0000] {processor.py:153} INFO - Started process (PID=1996) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:39:08.294+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T08:39:08.337+0000] {logging_mixin.py:137} INFO - [2023-02-18T08:39:08.336+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:39:08.519+0000] {logging_mixin.py:137} INFO - [2023-02-18T08:39:08.438+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T08:39:08.521+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T08:39:10.686+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 2.688 seconds
[2023-02-18T09:51:18.282+0000] {processor.py:153} INFO - Started process (PID=137) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T09:51:18.340+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T09:51:18.539+0000] {logging_mixin.py:137} INFO - [2023-02-18T09:51:18.539+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T09:51:19.411+0000] {logging_mixin.py:137} INFO - [2023-02-18T09:51:19.274+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T09:51:19.450+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T09:51:20.774+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 2.812 seconds
[2023-02-18T09:53:20.006+0000] {processor.py:153} INFO - Started process (PID=232) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T09:53:20.021+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T09:53:20.023+0000] {logging_mixin.py:137} INFO - [2023-02-18T09:53:20.023+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T09:53:20.093+0000] {logging_mixin.py:137} INFO - [2023-02-18T09:53:20.078+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T09:53:20.094+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T09:53:20.386+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 0.429 seconds
[2023-02-18T09:53:58.720+0000] {processor.py:153} INFO - Started process (PID=273) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T09:53:58.736+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T09:53:58.768+0000] {logging_mixin.py:137} INFO - [2023-02-18T09:53:58.767+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T09:53:59.040+0000] {logging_mixin.py:137} INFO - [2023-02-18T09:53:58.920+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T09:53:59.042+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T09:53:59.583+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 0.902 seconds
[2023-02-18T09:54:40.570+0000] {processor.py:153} INFO - Started process (PID=312) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T09:54:40.602+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T09:54:40.604+0000] {logging_mixin.py:137} INFO - [2023-02-18T09:54:40.604+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T09:54:40.916+0000] {logging_mixin.py:137} INFO - [2023-02-18T09:54:40.914+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T09:54:40.930+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T09:54:41.281+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 0.820 seconds
[2023-02-18T09:55:48.016+0000] {processor.py:153} INFO - Started process (PID=371) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T09:55:48.160+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T09:55:48.176+0000] {logging_mixin.py:137} INFO - [2023-02-18T09:55:48.175+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T09:55:48.347+0000] {logging_mixin.py:137} INFO - [2023-02-18T09:55:48.344+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T09:55:48.447+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T09:55:49.579+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 1.794 seconds
[2023-02-18T09:58:21.818+0000] {processor.py:153} INFO - Started process (PID=463) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T09:58:21.880+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T09:58:21.881+0000] {logging_mixin.py:137} INFO - [2023-02-18T09:58:21.881+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T09:58:22.209+0000] {logging_mixin.py:137} INFO - [2023-02-18T09:58:22.196+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T09:58:22.210+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T09:58:22.731+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 1.043 seconds
[2023-02-18T10:00:32.650+0000] {processor.py:153} INFO - Started process (PID=556) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T10:00:32.757+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T10:00:32.775+0000] {logging_mixin.py:137} INFO - [2023-02-18T10:00:32.774+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T10:00:33.411+0000] {logging_mixin.py:137} INFO - [2023-02-18T10:00:33.363+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T10:00:33.413+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T10:00:34.876+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 2.457 seconds
[2023-02-18T10:02:03.096+0000] {processor.py:153} INFO - Started process (PID=620) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T10:02:03.114+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T10:02:03.250+0000] {logging_mixin.py:137} INFO - [2023-02-18T10:02:03.249+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T10:02:03.860+0000] {logging_mixin.py:137} INFO - [2023-02-18T10:02:03.788+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T10:02:03.862+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T10:02:05.349+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 2.426 seconds
[2023-02-18T10:04:06.655+0000] {processor.py:153} INFO - Started process (PID=704) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T10:04:06.679+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T10:04:06.725+0000] {logging_mixin.py:137} INFO - [2023-02-18T10:04:06.681+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T10:04:07.423+0000] {logging_mixin.py:137} INFO - [2023-02-18T10:04:07.175+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T10:04:07.424+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T10:04:09.262+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 2.843 seconds
[2023-02-18T10:07:03.607+0000] {processor.py:153} INFO - Started process (PID=808) to work on /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T10:07:03.780+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_ingestion_local.py for tasks to queue
[2023-02-18T10:07:03.783+0000] {logging_mixin.py:137} INFO - [2023-02-18T10:07:03.782+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T10:07:04.625+0000] {logging_mixin.py:137} INFO - [2023-02-18T10:07:04.563+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local.py", line 7, in <module>
    from ingest_script import ingest_callable
ModuleNotFoundError: No module named 'ingest_script'
[2023-02-18T10:07:04.626+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local.py
[2023-02-18T10:07:06.270+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_ingestion_local.py took 3.091 seconds
